[project]
name = "odoo-addons-oca-server-tools"
version = "18.0.20241010.1"
dependencies = [
    "odoo-addon-jsonifier==18.0.*",
    "odoo-addon-onchange_helper==18.0.*",
]
classifiers=[
    "Programming Language :: Python",
    "Framework :: Odoo",
    "Framework :: Odoo :: 18.0",
]
